<?php
return  array(
    'columns'=>array(
        'pay_id'=>array(
            'type'=>'number',
            //'pkey' => true,
            'autoincrement' => true,
            //'extra' => 'auto_increment',
            'required' => true,
            'order' => 1,
            'label' => app::get('sysshop')->_('支付企业信息id'),
            'comment' => app::get('sysshop')->_('支付企业信息id 自增'),
        ),
        'OrgCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'in_list'=>true,
            'default_in_list'=>true,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('企业组织机构代码'),
            'comment' => app::get('sysshop')->_('企业组织机构代码'),
        ),
        'CopCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'in_list'=>true,
            'default_in_list'=>true,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('企业海关注册码'),
            'comment' => app::get('sysshop')->_('企业海关注册码'),
        ),
        'CopName'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 50,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('企业海关注册名称'),
            'comment' => app::get('sysshop')->_('企业海关注册名称'),
            'order' => 10,
        ),
        'SenderID'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 30,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('发送方'),
            'comment' => app::get('sysshop')->_('发送方'),
            'order' => 10,
        ),
        'ReceiverDepartment'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 30,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('接收部门'),
            'comment' => app::get('sysshop')->_('接收部门'),
            'order' => 10,
        ),
        'payCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'in_list'=>true,
            'default_in_list'=>true,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('海关注册登记编号'),
            'comment' => app::get('sysshop')->_('海关注册登记编号'),
        ),
        'payName'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 50,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('海关注册登记名称'),
            'comment' => app::get('sysshop')->_('海关注册登记名称'),
            'order' => 10,
        ),
        'appType'=>array(
            //'type'=>'char(18)',
            'type' => 'bool',
            'required'=>true,
            'default' => 1,
            'label' => app::get('sysshop')->_('报送类型'),
            'comment' => app::get('sysshop')->_('报送类型,1-新增 2-变更。默认为1'),
        ),
        'appStatus'=>array(
            //'type'=>'char(18)',
            'type' => 'bool',
            'required'=>true,
            'default' => 1,
            'label' => app::get('sysshop')->_('业务状态'),
            'comment' => app::get('sysshop')->_('业务状态,1-暂存，2-申报，默认为2'),
        ),
    ),
    'primary' => 'pay_id',
    'comment' => app::get('sysshop')->_('支付企业信息'),
);


