<?php
return  array(
    'columns'=>array(
        'infor_id'=>array(
            'type'=>'number',
            //'pkey' => true,
            'autoincrement' => true,
            //'extra' => 'auto_increment',
            'required' => true,
            'order' => 1,
            'label' => app::get('sysshop')->_('企业信息id'),
            'comment' => app::get('sysshop')->_('企业信息id 自增'),
        ),
        'shop_id'=>array(
            'type'=>'table:shop',
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'label' => app::get('sysshop')->_('商家店铺id'),
            'comment' => app::get('sysshop')->_('商家店铺id'),
            'order' => 6,
        ),
        'OrgCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('企业组织机构代码'),
            'comment' => app::get('sysshop')->_('企业组织机构代码'),
        ),
        'CopCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('传输企业代码'),
            'comment' => app::get('sysshop')->_('传输企业代码'),
        ),
        'CopName'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 50,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('传输企业名称'),
            'comment' => app::get('sysshop')->_('传输企业名称'),
            'order' => 10,
        ),
        'SenderID'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 30,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('发送方'),
            'comment' => app::get('sysshop')->_('发送方'),
            'order' => 10,
        ),
        'ReceiverDepartment'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 30,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('接收部门'),
            'comment' => app::get('sysshop')->_('接收部门'),
            'order' => 10,
        ),
        'ebpCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('电商平台代码'),
            'comment' => app::get('sysshop')->_('电商平台代码'),
        ),
        'ebpName'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 50,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('电商平台企业名称'),
            'comment' => app::get('sysshop')->_('电商平台企业名称'),
            'order' => 10,
        ),
        'ebcCode'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 20,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('电商商户代码'),
            'comment' => app::get('sysshop')->_('电商商户代码'),
        ),
        'ebcName'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 50,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('电商商户名称'),
            'comment' => app::get('sysshop')->_('电商商户名称'),
            'order' => 10,
        ),
        'payID'=>array(
            'type'=>'table:account@sysshop',//?
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'label' => app::get('sysshop')->_('支付企业'),
            'comment' => app::get('sysshop')->_('支付企业id'),
            'order' => 6,
        ),
        'logisticsID'=>array(
            'type'=>'table:shop',
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'label' => app::get('sysshop')->_('物流企业'),
            'comment' => app::get('sysshop')->_('物流企业id'),
            'order' => 6,
        ),
        'declarationID'=>array(
            'type'=>'table:account@sysshop',
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'label' => app::get('sysshop')->_('报关企业'),
            'comment' => app::get('sysshop')->_('报关企业id'),
            'order' => 6,
        ),
        'signID'=>array(
            'type'=>'table:account@sysshop',
            'required'=>true,
            'label' => app::get('sysshop')->_('承运企业'),
            'comment' => app::get('sysshop')->_('承运企业id'),
            'order' => 6,
        ),
        'appType'=>array(
            //'type'=>'char(18)',
            'type' => 'bool',
            'required'=>true,
            'default' => 1,
            'label' => app::get('sysshop')->_('报送类型'),
            'comment' => app::get('sysshop')->_('报送类型,1-新增 2-变更。默认为1'),
        ),
        'appStatus'=>array(
            //'type'=>'char(18)',
            'type' => 'bool',
            'required'=>true,
            'default' => 1,
            'label' => app::get('sysshop')->_('业务状态'),
            'comment' => app::get('sysshop')->_('业务状态,1-暂存，2-申报，默认为2'),
        ),
    ),
    'primary' => 'infor_id',
    'index' => array(

        'ind_shop_id' => ['columns' => ['shop_id']],
        'ind_pay_id' => ['columns' => ['payID']],
        'ind_logistics_id' => ['columns' => ['logisticsID']],
        'ind_declaration_id' => ['columns' => ['declarationID']],
    ),
    'comment' => app::get('sysshop')->_('企业报文表'),
);


