<?php
return  array(
    'columns'=>array(
        'id'=>array(
            'type'=>'number',
            //'pkey' => true,
            'autoincrement' => true,
            //'extra' => 'auto_increment',
            'required' => true,
            'order' => 1,
            'label' => app::get('sysshop')->_('id'),
            'comment' => app::get('sysshop')->_('id 自增'),
        ),
        'code'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 40,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('行政区划代码'),
            'comment' => app::get('sysshop')->_('行政区划代码'),
        ),
        'province'=>array(
            //'type'=>'varchar(20)',
            'type' => 'string',
            'length' => 40,
            'required'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('省份'),
            'comment' => app::get('sysshop')->_('省份'),
        ),
        'city'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 40,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('城市'),
            'comment' => app::get('sysshop')->_('城市'),
            'order' => 10,
        ),
        'district'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 30,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('区'),
            'comment' => app::get('sysshop')->_('区'),
            'order' => 10,
        ),
        'parent'=>array(
            //'type'=>'varchar(50)',
            'type' => 'string',
            'length' => 30,
            'required'=>true,
            'in_list'=>true,
            'default_in_list'=>true,
            'filtertype' => false,
            'filterdefault' => 'true',
            'label' => app::get('sysshop')->_('父级id'),
            'comment' => app::get('sysshop')->_('父级id'),
            'order' => 10,
        ),
    ),
    'primary' => 'id',
    'comment' => app::get('sysshop')->_('最新行政区划省市区'),
);


